pipeline{
    agent any
        tools{
             maven 'Maven'
            }
    stages{
        stage('SCM Pull'){
            steps{
                echo "Git Checkout Started"
                  }
          }
}
