version: 0.1

phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - mvn test
      - docker build . -t styagi935/simple-app:7.0.0
artifacts:
  files:
    - '**/*'
