
pipeline{
    agent any
    tools{
  maven 'Maven'
    }
    stages{
        stage('SCM Pull'){
            steps{
                echo "Git Checkout Started"
                  git url: 'https://github.com/styagi935/demo.git'
                echo "Git Checkout Completed"
            }
        }
        stage('Maven Build'){
            steps{
                echo "Maven Build Started"
                sh "mvn clean package"
                echo "Maven Build is successful"
            }
        }
