---
 - name: User
   hosts: slave
   become: true
   become_user: root
   gather_facts: false
   vars:
     user_name: 
   tasks:
     - name: Create New User
       ansible.builtin.user:
          name: "{{ user_name }}"
