---
 - name: Nexus Download file
   hosts: slave
   become: true
   gather_facts: yes
   vars:
    user_name: satpute
   tasks:
     - name: To Create the User
       ansible.builtin.user:
          name: "{{ user_name }}"
