---
 - name: User
   hosts: slave
   become: true
   gather_facts: no
   vars:
     user_name: ansh
   tasks:
     - name: Create New User
       ansible.builtin.user:
          name: "{{ user_name }}"
