---
 - name: Nexus Download file
   hosts: master
   become: true
   gather_facts: yes
   tasks:
     - name: Download the War file from nexus
       ansible.builtin.get_url:
         url: "http://{{ nexus_url }}/service/rest/v1/search/assets/download?sort=version&repository=Sample-app&maven.groupId=in.javahome&maven.artifactId=simple-app&maven.extension=war"
         username: "{{ nexus_user }}"
         password: "{{ nexus_password }}"
         dest: /etc/ansible/      
       
     - name: Rename The file also Copy to the Slave Node
       command: ./rename_artifact.sh
       args:
         chdir: /etc/ansible
