---
# tasks file for tomcat
- name: Install Java
  ansible.builtin.yum:
     name: java
     state: installed
- name: Download the Tomcat Package
  ansible.builtin.get_url:
      url: "{{ tomcat_url }}"
      dest: /opt/
      mode: '0755'
- name: Untar the tomcat File
  ansible.builtin.unarchive:
     src: /opt/{{ tomcat_pck }}.tar.gz
     dest: /opt/
     remote_src: yes
- name: Chnage the Permision of the tomcat File
  ansible.builtin.file:
     path: /opt/{{ tomcat_pck }}/
     mode: '0755'
     recurse: yes
     state: directory
- name: Create the Link for the startup.sh
  ansible.builtin.file:
    src: /opt/{{ tomcat_pck }}/bin/startup.sh
    dest: /usr/local/bin/tomcatup
    state: link
- name: Create the Link for Shutdown.sh
  ansible.builtin.file:
     src: /opt/{{ tomcat_pck }}/bin/shutdown.sh
     dest: /usr/local/bin/tomcatdown
     state: link
- name: Ansible Templete for tomcat-users.xml
  ansible.builtin.copy:
    src: /opt/tomcatusers.xml
    dest: /opt/{{ tomcat_pck }}/conf/tomcat-users.xml
    remote_src: yes
    
- name: Ansible Templete For Context.xml
  ansible.builtin.copy:
    src: /opt/context.xml
    dest: /opt/{{ tomcat_pck }}/webapps/manager/META-INF/
    remote_src: yes
    
- name: Remove the Existing War file
  command: rm -rf *.war
  args:
    chdir: /opt/{{ tomcat_pck }}/webapps/
- name: download  Artifact from the nexus
  ansible.builtin.get_url:
    url: "http://{{ nexus_Ip }}/service/rest/v1/search/assets/download?sort=version&repository=Sample-app&maven.groupId={{ group_Id }}&maven.artifactId={{ artifact_Id }}&maven.extension=war"
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    dest: /opt/{{ tomcat_pck }}/webapps/
    remote_src: yes
- name: Restart the Tomcat Server
  shell: /opt/{{ tomcat_pck }}/bin/shutdown.sh && nohup /opt/{{ tomcat_pck }}/bin/startup.sh
