---
# tasks file for nexus
- name: Downloading start
  ansible.builtin.get_url:
     url: http://{{ nexus_url }}/service/rest/v1/search/assets/download?sort=version&repository={{ repo_name }}&maven.groupId={{ grp_id }}&maven.artifactId={{ art_id }}&maven.extension=war
     username: "{{ nexus_user }}"
     password: "{{ nexus_password }}"
     dest: /etc/ansible/
- name: Remove and Copying the file
  command: ./rename_artifact.sh
  args:
    chdir: /etc/ansible/simple-app/
