---
# tasks file for tomcat
- name: Install Java
  ansible.builtin.yum:
     name: java
     state: installed
- name: Download the Tomcat Package
  ansible.builtin.get_url:
      url: "{{ tomcat_url }}"
      dest: /opt/
      mode: '0755'
- name: Untar the tomcat File
  ansible.builtin.unarchive:
     src: /opt/apache-tomcat-9.0.70.tar.gz
     dest: /opt/
     remote_src: yes
- name: Chnage the Permision of the tomcat File
  ansible.builtin.file:
     path: /opt/apache-tomcat-9.0.70/
     mode: '0755'
     recurse: yes
     state: directory
- name: Create the Link for the startup.sh
  ansible.builtin.file:
    src: /opt/apache-tomcat-9.0.70/bin/startup.sh
    dest: /usr/local/bin/tomcatup
    state: link
- name: Create the Link for Shutdown.sh
  ansible.builtin.file:
     src: /opt/apache-tomcat-9.0.70/bin/shutdown.sh
     dest: /usr/local/bin/tomcatdown
     state: link
- name: Ansible Templete for tomcat-users.xml
  ansible.builtin.template:
    src: tomcat-users.xml.j2
    dest: /opt/apache-tomcat-9.0.70/conf/tomcat-users.xml
    remote_src: false
    mode: '0640'
    owner: root
    group: root
    backup: yes
- name: Ansible Templete For Context.xml
  ansible.builtin.template:
    src: context.xml.j2 
    dest: /opt/apache-tomcat-9.0.70/webapps/manager/META-INF/context.xml
    remote_src: false
    mode: '0640'
    owner: root
    group: root
    backup: yes
- name: Restart the Tomcat Server
  shell: /opt/apache-tomcat-9.0.70/bin/shutdown.sh && nohup /opt/apache-tomcat-9.0.70/bin/startup.sh
